name: Conformance

on:
  push:
    branches: [ 'main', 'release-*' ]
  pull_request:
    branches: [ 'main', 'release-*' ]

jobs:

  conformance:
    name: CloudEvents
    strategy:
      matrix:
        go-version: [1.21.x]
        platform: [ubuntu-latest]

    runs-on: ${{ matrix.platform }}

    steps:
      - name: Checkout code
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

      - name: Setup Go ${{ matrix.go-version }}
        uses: actions/setup-go@0a12ed9d6a96ab950c8f026ed9f722fe0da7ef32 # v5.0.2
        with:
          go-version: ${{ matrix.go-version }}
          cache-dependency-path: v2/go.sum
        id: go

      - name: Update git submodule
        run: git submodule sync && git submodule update --init

      - name: Build
        run: ./hack/conformance-test.sh

