name: Go Format

on:
  push:
    branches: [ 'main', 'release-*' ]
  pull_request:
    branches: [ 'main', 'release-*' ]

permissions:
  contents: read
  
jobs:

  format:
    name: Format
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4.2.1

      - name: Setup Go
        uses: actions/setup-go@0a12ed9d6a96ab950c8f026ed9f722fe0da7ef32 # v5.0.2
        with:
          go-version: 1.23
          cache-dependency-path: v2/go.sum
        id: go

      - name: Go Format
        shell: bash
        run: |
          gofmt -s -w $(find -type f -name '*.go' -print)

      - name: Verify
        shell: bash
        run: |
          if [[ $(git diff-index --name-only HEAD --) ]]; then
              echo "Found diffs in:"
              git diff-index --name-only HEAD --
              echo "${{ github.repository }} is out of style. Please run go fmt."
              exit 1
          fi
          echo "${{ github.repository }} is formatted correctly."
