name: Unit Test

on:
  push:
    branches: [ 'main', 'release-*' ]
  pull_request:
    branches: [ 'main', 'release-*' ]

permissions:
  contents: read
  
jobs:

  test:
    name: Unit Test
    strategy:
      matrix:
        go-version: [1.21.x]
        platform: [ubuntu-latest]

    runs-on: ${{ matrix.platform }}

    steps:
      - name: Checkout code
        uses: actions/checkout@d632683dd7b4114ad314bca15554477dd762a938 # v4.2.0

      - name: Setup Go ${{ matrix.go-version }}
        uses: actions/setup-go@0a12ed9d6a96ab950c8f026ed9f722fe0da7ef32 # v5.0.2
        with:
          go-version: ${{ matrix.go-version }}
          cache-dependency-path: v2/go.sum
        id: go

      - name: Test
        run: ./hack/unit-test.sh
