name: Inclusive

on:
  pull_request:
    branches: [ 'main', 'release-*' ]

permissions:
  contents: read
  
jobs:

  language:
    name: Language
    runs-on: ubuntu-latest

    steps:

      - name: Checkout code
        uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4.2.1

      - name: Woke
        uses: get-woke/woke-action-reviewdog@d71fd0115146a01c3181439ce714e21a69d75e31 # v0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-review